import Head from 'next/head'
import Image from 'next/image'
import { useState } from "react";
import styles from '../styles/Home.module.css'

export default function Home() {
  const [prompt, setPrompt] = useState("")
  const [imgurl, setImgurl] = useState("")
  const [loading, setLoading] = useState(false);

  async function onSubmit(event) {
    event.preventDefault();
    if (loading) {
      return;
    }
    setLoading(true);
    setPrompt('');
    const response = await fetch("/api/generate", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({prompt : prompt}),
    });

    const data = await response.json();
    setImgurl(data.result);
    console.log(data.result,'data.result')
    setPrompt("");
    setLoading(false);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Generate image from Text</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h4 >Try DALL.E 2 <br></br> <h5>Generate an Image from text using OpenAi</h5>   </h4>
        <form onSubmit={onSubmit}>
          <input
            type="text"
            name="prompt"
            placeholder='type something to generate an Image ...'
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
          />
          <input type="submit" value="Generate Image" />
        </form>
        { loading== true ? (
          <div>
            <h3> DALL.E is Creating  your image .. 🪄💡</h3>
            <img src="/loading.gif" className={styles.loading} />
          </div>
        ) : (
          <div className={styles.imagecontainer}>
          {imgurl &&
          <Image
            className={styles.resultimage}
            src={imgurl}
            alt='Image'
            width={370}
            height={380}
          />
          }
        </div> 
        )
    }
        </main>
    </div>
  )
}
